global using System;
global using System.Collections.Generic;
//global using System.ComponentModel;
//global using System.ComponentModel.DataAnnotations;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Runtime.Serialization;
global using Orders.Application.Contracts.ViewModel;